services:
  postgres:
    image: postgres:16
    container_name: trackiny-db
    environment:
      POSTGRES_USER: trackiny
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: trackiny
    ports:
      - "5432:5432"